##
## sample kubic-init configuration file for cilium
##
apiVersion: kubic.suse.com/v1alpha2
kind: KubicInitConfiguration
runtime:
  engine: docker
network:
  multipleCni: true
  cni:
    driver: cilium
